# Generated by Django 5.2.8 on 2025-11-11 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('appearances', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'story_characters',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('location_type', models.CharField(blank=True, max_length=100)),
                ('scenes', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'story_locations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('raw_text', models.TextField()),
                ('parsed_data', models.JSONField(default=dict)),
                ('summary', models.TextField(blank=True)),
                ('total_shots', models.IntegerField(default=0)),
                ('estimated_total_time', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shot_number', models.IntegerField()),
                ('description', models.TextField()),
                ('camera_angle', models.CharField(blank=True, max_length=100)),
                ('complexity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('estimated_time', models.CharField(blank=True, max_length=100)),
                ('special_requirements', models.JSONField(blank=True, default=list)),
                ('characters', models.ManyToManyField(blank=True, related_name='shots', to='ai_machines.character')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shots', to='ai_machines.location')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='ai_machines.story')),
            ],
            options={
                'db_table': 'story_shots',
                'ordering': ['shot_number'],
            },
        ),
        migrations.AddField(
            model_name='location',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='ai_machines.story'),
        ),
        migrations.AddField(
            model_name='character',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='ai_machines.story'),
        ),
        migrations.CreateModel(
            name='StoryAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('asset_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('complexity', models.CharField(default='medium', max_length=20)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_assets', to='ai_machines.story')),
            ],
            options={
                'db_table': 'story_assets',
                'ordering': ['name'],
            },
        ),
    ]
