# Generated by Django 5.2.8 on 2025-11-13 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_machines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('estimated_time', models.CharField(blank=True, max_length=100)),
                ('total_shots', models.IntegerField(default=0)),
                ('characters', models.ManyToManyField(blank=True, related_name='sequences', to='ai_machines.character')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sequences', to='ai_machines.location')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='ai_machines.story')),
            ],
            options={
                'db_table': 'story_sequences',
                'ordering': ['sequence_number'],
            },
        ),
        migrations.AddField(
            model_name='shot',
            name='sequence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='ai_machines.sequence'),
        ),
    ]
