# Generated by Django 5.2.8 on 2025-11-15 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_machines', '0002_sequence_shot_sequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtControlSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_colors', models.JSONField(default=list)),
                ('color_mood', models.CharField(choices=[('warm', 'Warm'), ('cool', 'Cool'), ('neutral', 'Neutral')], default='neutral', max_length=50)),
                ('color_saturation', models.CharField(choices=[('high', 'High Saturation'), ('medium', 'Medium Saturation'), ('low', 'Low Saturation'), ('desaturated', 'Desaturated')], default='medium', max_length=50)),
                ('color_contrast', models.CharField(choices=[('high', 'High Contrast'), ('medium', 'Medium Contrast'), ('low', 'Low Contrast')], default='medium', max_length=50)),
                ('forbidden_colors', models.JSONField(default=list)),
                ('composition_style', models.CharField(choices=[('rule_of_thirds', 'Rule of Thirds'), ('symmetrical', 'Symmetrical'), ('asymmetrical', 'Asymmetrical'), ('centered', 'Centered'), ('dynamic', 'Dynamic')], default='rule_of_thirds', max_length=50)),
                ('preferred_shot_types', models.JSONField(default=list)),
                ('handheld_allowed', models.BooleanField(default=False)),
                ('stable_camera_allowed', models.BooleanField(default=True)),
                ('gimbal_allowed', models.BooleanField(default=True)),
                ('drone_allowed', models.BooleanField(default=False)),
                ('static_camera_allowed', models.BooleanField(default=True)),
                ('wide_angle_allowed', models.BooleanField(default=True)),
                ('standard_lens_preferred', models.BooleanField(default=True)),
                ('telephoto_allowed', models.BooleanField(default=True)),
                ('macro_allowed', models.BooleanField(default=False)),
                ('fisheye_allowed', models.BooleanField(default=False)),
                ('static_shots_only', models.BooleanField(default=False)),
                ('panning_allowed', models.BooleanField(default=True)),
                ('tracking_allowed', models.BooleanField(default=True)),
                ('zoom_allowed', models.BooleanField(default=True)),
                ('dolly_shots_allowed', models.BooleanField(default=True)),
                ('art_style', models.CharField(choices=[('realistic', 'Realistic'), ('stylized', 'Stylized'), ('cartoon', 'Cartoon'), ('anime', 'Anime'), ('watercolor', 'Watercolor'), ('oil_painting', 'Oil Painting'), ('digital_art', 'Digital Art')], default='realistic', max_length=50)),
                ('detail_level', models.CharField(choices=[('high', 'High Detail'), ('medium', 'Medium Detail'), ('low', 'Low Detail')], default='medium', max_length=50)),
                ('lighting_style', models.CharField(choices=[('natural', 'Natural Lighting'), ('dramatic', 'Dramatic Lighting'), ('soft', 'Soft Lighting'), ('high_key', 'High Key'), ('low_key', 'Low Key')], default='natural', max_length=50)),
                ('animation_type', models.CharField(choices=[('smooth', 'Smooth/Realistic'), ('stylized', 'Stylized/Exaggerated'), ('stop_motion', 'Stop-Motion Style'), ('2d_style', '2D Animation Style')], default='smooth', max_length=50)),
                ('motion_preference', models.CharField(choices=[('fast', 'Fast-Paced'), ('slow', 'Slow and Deliberate'), ('natural', 'Natural Timing'), ('exaggerated', 'Exaggerated Timing')], default='natural', max_length=50)),
                ('style_reference_images', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('story', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='art_control', to='ai_machines.story')),
            ],
            options={
                'db_table': 'art_control_settings',
                'ordering': ['-updated_at'],
            },
        ),
    ]
