# Generated by Django 5.2.8 on 2025-11-15 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_machines', '0003_artcontrolsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artcontrolsettings',
            name='aspect_ratio',
            field=models.CharField(blank=True, choices=[('16:9', '16:9 (Widescreen)'), ('21:9', '21:9 (Ultrawide)'), ('4:3', '4:3 (Standard)'), ('1:1', '1:1 (Square)'), ('9:16', '9:16 (Portrait)'), ('custom', 'Custom')], default='16:9', max_length=20),
        ),
        migrations.AddField(
            model_name='artcontrolsettings',
            name='custom_aspect_ratio',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='artcontrolsettings',
            name='sequence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='art_control', to='ai_machines.sequence'),
        ),
        migrations.AddField(
            model_name='artcontrolsettings',
            name='shot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='art_control', to='ai_machines.shot'),
        ),
        migrations.AlterField(
            model_name='artcontrolsettings',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='art_control', to='ai_machines.story'),
        ),
        migrations.AddConstraint(
            model_name='artcontrolsettings',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('story__isnull', False), ('sequence__isnull', True), ('shot__isnull', True)), models.Q(('story__isnull', True), ('sequence__isnull', False), ('shot__isnull', True)), models.Q(('story__isnull', True), ('sequence__isnull', True), ('shot__isnull', False)), _connector='OR'), name='exactly_one_parent'),
        ),
    ]
