# Generated by Django 5.2.8 on 2025-11-15 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_machines', '0004_artcontrolsettings_aspect_ratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artcontrolsettings',
            name='atmosphere',
            field=models.CharField(blank=True, choices=[('foggy', 'Foggy'), ('clear', 'Clear'), ('dusty', 'Dusty'), ('ethereal', 'Ethereal'), ('misty', 'Misty'), ('hazy', 'Hazy'), ('crisp', 'Crisp')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='artcontrolsettings',
            name='frame_rate',
            field=models.CharField(blank=True, choices=[('24', '24 fps (Cinematic)'), ('30', '30 fps (Standard)'), ('60', '60 fps (Smooth)'), ('120', '120 fps (High Frame Rate)')], default='24', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='artcontrolsettings',
            name='mood_board_images',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='artcontrolsettings',
            name='resolution',
            field=models.CharField(blank=True, choices=[('1080p', '1080p (Full HD)'), ('2K', '2K (1440p)'), ('4K', '4K (2160p)'), ('8K', '8K (4320p)')], default='1080p', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='artcontrolsettings',
            name='shot_duration',
            field=models.CharField(blank=True, choices=[('fast_paced', 'Fast-Paced (Quick Cuts)'), ('standard', 'Standard'), ('slow_paced', 'Slow-Paced (Long Takes)')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='artcontrolsettings',
            name='time_of_day',
            field=models.CharField(blank=True, choices=[('dawn', 'Dawn'), ('day', 'Day'), ('dusk', 'Dusk'), ('night', 'Night'), ('golden_hour', 'Golden Hour'), ('blue_hour', 'Blue Hour')], max_length=50, null=True),
        ),
    ]
