# Generated by Django 5.2.8 on 2025-11-26 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_machines', '0007_chat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('talent_type', models.CharField(choices=[('voice_actor', 'Voice Actor'), ('3d_artist', '3D Artist'), ('modeler', '3D Modeler'), ('animator', 'Animator'), ('rigger', 'Rigger'), ('texture_artist', 'Texture Artist'), ('lighting_artist', 'Lighting Artist'), ('compositor', 'Compositor'), ('other', 'Other')], max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('portfolio_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('daily_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('availability_status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('unavailable', 'Unavailable')], default='available', max_length=20)),
                ('specializations', models.JSONField(blank=True, default=list)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_talent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'talent_pool',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShotTalentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('animator', 'Animator'), ('lighting_artist', 'Lighting Artist'), ('compositor', 'Compositor'), ('fx_artist', 'FX Artist')], default='animator', max_length=50)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('contacted', 'Contacted'), ('negotiating', 'Negotiating'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='proposed', max_length=20)),
                ('rate_agreed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_hours', models.IntegerField(blank=True, null=True)),
                ('actual_hours', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_assignments', to='ai_machines.shot')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shot_assignments', to='ai_machines.talent')),
            ],
            options={
                'db_table': 'shot_talent_assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetTalentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('modeler', '3D Modeler'), ('texture_artist', 'Texture Artist'), ('rigger', 'Rigger'), ('concept_artist', 'Concept Artist')], default='modeler', max_length=50)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('contacted', 'Contacted'), ('negotiating', 'Negotiating'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='proposed', max_length=20)),
                ('rate_agreed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_hours', models.IntegerField(blank=True, null=True)),
                ('actual_hours', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_assignments', to='ai_machines.storyasset')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_assignments', to='ai_machines.talent')),
            ],
            options={
                'db_table': 'asset_talent_assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='CharacterTalentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('voice_actor', 'Voice Actor'), ('motion_capture', 'Motion Capture'), ('reference_model', 'Reference Model')], default='voice_actor', max_length=50)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('contacted', 'Contacted'), ('negotiating', 'Negotiating'), ('confirmed', 'Confirmed'), ('completed', 'Completed')], default='proposed', max_length=20)),
                ('rate_agreed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talent_assignments', to='ai_machines.character')),
                ('talent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_assignments', to='ai_machines.talent')),
            ],
            options={
                'db_table': 'character_talent_assignments',
                'ordering': ['-assigned_at'],
                'unique_together': {('character', 'talent', 'role_type')},
            },
        ),
    ]
