# Generated by Django 5.2.8 on 2025-12-28 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_machines', '0008_talent_shottalentassignment_assettalentassignment_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='charactertalentassignment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='charactertalentassignment',
            name='character',
        ),
        migrations.RemoveField(
            model_name='charactertalentassignment',
            name='talent',
        ),
        migrations.RemoveField(
            model_name='shottalentassignment',
            name='shot',
        ),
        migrations.RemoveField(
            model_name='shottalentassignment',
            name='talent',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='AssetTalentAssignment',
        ),
        migrations.DeleteModel(
            name='CharacterTalentAssignment',
        ),
        migrations.DeleteModel(
            name='ShotTalentAssignment',
        ),
        migrations.DeleteModel(
            name='Talent',
        ),
    ]
